### ISSUE TITLE
Change log level of Cookie handler authentication message

### ISSUE THREAD

**Issue by leastprivilege** [aspnet/Security#1517]
Right now the cookie handler is using information level for this:

[10:31:24 Information] Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler
AuthenticationScheme: [scheme] was successfully authenticated.

This happens way too often (at least once per request) and fills up the log file with unnecessary information. Can we move that to debug level?

**Comment by Eilon** [comment]
Agreed. Leaving it up-for-grabs for anyone to fix, or we'll get to it when we can.

**Comment by leastprivilege** [comment]
Done https://github.com/aspnet/Security/pull/1522

**Comment by PinpointTownes** [comment]
It's worth noting that this change doesn't only affect the cookies handler, but all the handlers inheriting from `AuthenticationHandler` (third-party providers included).

**Comment by Tratcher** [comment]
True, but only handlers that can directly produce an identity like cookies, bearer, basic, etc... None of the remote providers are affected.

**Comment by PinpointTownes** [comment]
> None of the remote providers are affected.

That's not exact actually, as you can call `AuthenticateAsync("Facebook")`. Currently, it logs an `Information` message in both the sign-in scheme handler AND the remote handler.

I have no particular opinion about that, 'tho I think it will make debugging harder for beginners. I just wanted to point out that it may be considered as a functional breaking change (probably an acceptable one, though).

**Comment by Eilon** [comment]
Fixed in https://github.com/aspnet/Security/pull/1522.

**Comment by niemyjski** [comment]
@Eilon Is there any reason why I'm still seeing this even if my min level was info but I had an override for System and Microsoft for min level of warning? Looking at the extension methods I don't see where it's getting the log source from.
