### ISSUE TITLE
External login via Microsoft Account failed on RC2/RC3

### ISSUE THREAD

**Issue by LukaszDev** [aspnet/Security#866]
After moving my project to MVC Core RC2 I can't login via external Microsoft Account... Everything other works fine including login via Google Account.

It works perfectly on RC1 and nothing change directly in this part of my code after moving to RC2, of course I use new middleware - moreover I have updated authentication packages to RC3 and still have the same problem.

I'm pretty sure about my project/references/packages/etc. because I create new/clean project after installing RC2.

Here is my code form `Startup.cs`

```
...
app.UseIdentity();

// External Authentication
app.UseGoogleAuthentication(new GoogleOptions
{
     ClientId = Configuration["Authentication:Google:ClientId"],
     ClientSecret = Configuration["Authentication:Google:ClientSecret"],
     AutomaticAuthenticate = false
});

app.UseMicrosoftAccountAuthentication(new MicrosoftAccountOptions
{
     ClientId = Configuration["Authentication:MicrosoftAccount:ClientId"],
     ClientSecret = Configuration["Authentication:MicrosoftAccount:ClientSecret"],
     AutomaticAuthenticate = false
});

...
```

After first login I can see standard question about permission:

![msa](https://cloud.githubusercontent.com/assets/17419186/15801738/85bad744-2a96-11e6-9993-440349c5d1fd.png)

and after that I have an error:

```
An unhandled exception occurred while processing the request.

Exception: OAuth token endpoint failure: Status: BadRequest;Headers: Pragma: no-cache
 x-ms-request-id: 5d12a6bf-2178-42bc-9e51-7aa73b1d6c9e
 client-request-id: 05f7532f-0075-438f-80e4-efd85b641bde
 x-ms-gateway-service-instanceid: ESTSFE_IN_131
 X-Content-Type-Options: nosniff
 Strict-Transport-Security: max-age=31536000; includeSubDomains
 Cache-Control: no-store, no-cache
 P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
 Set-Cookie: x-ms-gateway-slice=productiona; path=/; secure; HttpOnly, stsservicecookie=ests; path=/
 Server: Microsoft-IIS/8.5
 X-Powered-By: ASP.NET
 Date: Fri, 03 Jun 2016 23:11:55 GMT
 ;Body: {"error":"invalid_request","error_description":"AADSTS90019: No tenant-identifying information found in either the request or implied by any provided credentials.\r\nTrace ID: 5d12a6bf-2178-42bc-9e51-7aa73b1d6c9e\r\nCorrelation ID: 05f7532f-0075-438f-80e4-efd85b641bde\r\nTimestamp: 2016-06-03 23:11:56Z","error_codes":[90019],"timestamp":"2016-06-03 23:11:56Z","trace_id":"5d12a6bf-2178-42bc-9e51-7aa73b1d6c9e","correlation_id":"05f7532f-0075-438f-80e4-efd85b641bde"};

Unknown location

AggregateException: Unhandled remote failure.

Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.<HandleRemoteCallbackAsync>d__5.MoveNext()

```

Each next attempt to login gives the same error (but without asking for permission).

**What can be wrong ?**

Thanks in advance for any advice.

**Comment by guylando** [comment]
I have the same problem.

**Comment by Tratcher** [comment]
MicrosoftAccount was moved to the new v2 endpoints which requires re-registering your application:
https://azure.microsoft.com/en-us/documentation/articles/active-directory-v2-app-registration/

Please try that and let us know if you are still having issues.

**Comment by LukaszDev** [comment]
Yes, Creating new app on https://apps.dev.microsoft.com following your instruction is solution in my case.

Now it's working perfectly. Thank you :)

**Comment by Brian-Ding** [comment]
how can set the directuri of my web application to be https:// instead of http:// after I deployed it to azure? 

thank you

**Comment by LukaszDev** [comment]
Please find my answer in original issue: [aspnet/Security#827 (comment)](https://github.com/aspnet/Security/issues/827#issuecomment-224452348).

**Comment by joeaudette** [comment]
I'm experiencing this same issue today, creating a new app did not solve it for me, I get the same error with the new app

Exception: OAuth token endpoint failure: Status: BadRequest;Headers: Cache-Control: no-store, no-cache
Date: Fri, 17 Jun 2016 19:27:21 GMT
Pragma: no-cache
P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
Server: Microsoft-IIS/8.5
Set-Cookie: esctx=AAABAAAAiL9Kn2Z27UubvWFPbm0gLf7i59miekjyoN3oZmvMWpPe2IxuvFDykAPUmR1G-ahpImow0nVRR5oFlYxJCje8oGOYgMrW8jUf6FdV0A8D7Ct6VTsyZ8hfh5HV1kLT2j0YsTcxE20az5bUlc13w6WPOZ-OxxJcjP7AaEhIDxl0U3vFwvU9t9PzWwJ2QLdrGgRvIAA; domain=.login.microsoftonline.com; path=/; secure; HttpOnly, x-ms-gateway-slice=productiona; path=/; secure; HttpOnly, stsservicecookie=ests; path=/; secure; HttpOnly
x-ms-request-id: 81d4172d-9c62-4483-8a5f-2ad594352c77
client-request-id: 3e1b637d-da38-412c-815f-f9b6074e39a7
x-ms-gateway-service-instanceid: ESTSFE_IN_375
X-Content-Type-Options: nosniff
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Powered-By: ASP.NET
;Body: {"error":"invalid_request","error_description":"AADSTS90019: No tenant-identifying information found in either the request or implied by any provided credentials.\r\nTrace ID: 81d4172d-9c62-4483-8a5f-2ad594352c77\r\nCorrelation ID: 3e1b637d-da38-412c-815f-f9b6074e39a7\r\nTimestamp: 2016-06-17 19:27:21Z","error_codes":[90019],"timestamp":"2016-06-17 19:27:21Z","trace_id":"81d4172d-9c62-4483-8a5f-2ad594352c77","correlation_id":"3e1b637d-da38-412c-815f-f9b6074e39a7"};

**Comment by LukaszDev** [comment]
> creating a new app did not solve it for me, I get the same error with the new app

I assume that new app is in new MS Service, then you have error:
```
error: invalid_request
error_description: AADSTS90019: No tenant-identifying information found in either the request or implied by any provided credentials
```

1. Basic question, but... are you using new `Client Id` and `Client Secret` in your web project ?

2. Are you using new `Microsoft.AspNetCore.Authentication.*` package - at least RC2 ?

**Comment by joeaudette** [comment]
1. yes 
2. yes RC2

Also all the other social auth providers are working for me.

And exactly like in your screen shot, when redirected to microsoft it appears to recognize my app credentials and prompt me that my app wants to access my profile

you can see my [startup here](https://github.com/joeaudette/cloudscribe/blob/master/src/example.WebApp/Startup.cs) which calls [extension methods here](https://github.com/joeaudette/cloudscribe/blob/master/src/cloudscribe.Core.Web/BuilderExtensions.cs) to configure the social auth middleware

I'm also fairly certain that I tested this soon after RC2 shipped and when I first ported to RC2 it was working correctly back then but I have not tested it again until today and found this problem only with Microsoft Account, not with any other providers. @PinpointTownes tried to help me on slack and pointed me here, so I deleted my previous application setup and created a new one per the post linked above. but I still get the same error with the new app that I created today

**Comment by LukaszDev** [comment]
Ok, looks like you are using `http` - but you should use `https` (ssl).

I have read about this requirement at official docs, but don't remember exactly where.

Looks also here: #827.

<br>From other things...

**1.** I see that you are using custom configuration of `Cookie Authentication` - I have no experience with this, so can't tell, but maybe this has impact on MsAccount middleware ?

**2.** Try use something like this:
```
if (!string.IsNullOrWhiteSpace(site.MicrosoftClientId)) 
{ 
   app.UseMicrosoftAccountAuthentication(new MicrosoftAccountOptions
   {
      ClientId = site.MicrosoftClientId,
      ClientSecret = site.MicrosoftClientSecret,
      AutomaticAuthenticate = false
   });
} 
```

**3.** Double check `ctx.Tenant` what is passed to `ClientId` and `ClientSecret` - maybe wrong or corrupted data are passed into - set debugger here, be sure!

**4.** Try - for test - not using `CallbackPath` - I had few problems with this in the past (RC1), but also I had no time to investigate it, so can't tell more.

**Comment by LukaszDev** [comment]
Reopen for @joeaudette.

**Comment by joeaudette** [comment]
correct clientid and secret are being used 

in the debugger it does not hit any errors in my own code and nothing looks corrupted in the data before it redirects to Microsoft. error seems to happen in the middleware after Microsoft redirects back to localhost

I am testing on localhost without ssl. It works for all the other providers ie google, facebook, twitter, all working for me. I would use ssl in production but I think it should work on localhost without that like the other ones do. I have not heard about any known issue with not using SSL for this scenario, I think there was an issue about that with Azure AD but I'm not using that.

**Comment by LukaszDev** [comment]
Yes, but https it's Ms Account recuierment, it's not middleware so it's not apply to other providers.

On old Ms App it's works well on both http and https, but - as far I know -  with new Ms App it's require to use https.

In my project I'm using https wit localhost and works well.

So maybe try that - it's simple and don't take a lot of time.

It's my last idea ;)

**Comment by joeaudette** [comment]
yeah it will probably work with ssl on localhost, and in production. I mainly posted here to make the team aware of the problem.
If the team considers this to be expected behavior then it would be good for one of them to say so here. If they do that then I would be satisfied if this issue is closed, but I think it should stay open until there is an official statement about it. If there is an official statement about it somewhere else please post a link because I have not seen any documentation saying that ssl is required for this. Since it works for other providers without that it seems expected that it would work for Microsoft account as well unless it is documented somewhere. 

The [article here about creating a new account](https://azure.microsoft.com/en-us/documentation/articles/active-directory-v2-app-registration/) does not say anything about ssl is required

or it would be better if the error message could say something like ssl is required

**Comment by PinpointTownes** [comment]
> or it would be better if the error message could say something like ssl is required

In theory, the authentication flow shouldn't fail at the token request stage for an invalid redirect_uri (e.g because it's not a HTTP address): it's too late for that. It's a requirement that should be enforced at the authorization request level, when redirecting the user to the Azure AD endpoint.

That said, I wouldn't be surprised if MSFT's OAuth2/OIDC sauce was not really spec-compliant. It wouldn't be the first time :smile:

**Comment by joeaudette** [comment]
yeah, if Microsoft does require ssl then when I create my app at apps.dev.microsoft.com and enter the redirect url they should not allow me to enter an url without https, that would make it very clear

**Comment by LukaszDev** [comment]
Like I said before: 'I don't remember exactly where' I read about this... so in other word I'm not sure about that! That's why I suggest test it ;)

For me it's working well, and unfortunately I have no idea what we can try else.

I have reopen this issue for you yesterday, so I hope someone from aspnet team will be able to help.

**Comment by LukaszDev** [comment]
Ok, Found it :)

Is mentioned about this in two place:

 - docs: [Restrictions on app registrations]():

>**The redirect_uri for web apps and services must begin with the scheme or https**, while the redirect_uri for all other platforms must use the hard-coded value of urn:ietf:oauth:2.0:oob.


- when you trying register app:

![image](https://cloud.githubusercontent.com/assets/17419186/16173686/5aff6d2e-35a1-11e6-966c-31e7b27b7644.png)

So, my question is - are you sure that you use new app platform v2 ?
Looks, like registration form not allow you to register 'http' - so, how you can use it ;)

**Comment by joeaudette** [comment]
yes I'm using a new app endpoint v2
it still allows you to enter an url with http://localhost...
if you type a few more characters that warning goes away, it does not prevent you, please try again and see for yourself
http:// is not valid and is blocked
http://localhost is valid and allowed
http://somedomain is valid and allowed

I admit the warning would make you think https is required but it is not enforced, if it really is required it should not allow me to save an url without https

**Comment by PinpointTownes** [comment]
@joeaudette but just to make sure, you should try with a HTTPS address.

**Comment by joeaudette** [comment]
ok, just tested with ssl and I still get the same error:

An unhandled exception occurred while processing the request.

Exception: OAuth token endpoint failure: Status: BadRequest;Headers: Cache-Control: no-store, no-cache
Date: Sun, 19 Jun 2016 20:02:49 GMT
Pragma: no-cache
P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
Server: Microsoft-IIS/8.5
Set-Cookie: esctx=AAABAAAAiL9Kn2Z27UubvWFPbm0gLX2WDMlTMbAZoZK4GxZGFip2pWdVap8qVDSYmPkqCfUR8R1CkRivAKNQLMsbOwwYd2UXB8x0_DtdKllOh_DN_0YifSbRSGugHkuxXamARQnQV8ugx-IXSiqaSukm8sGFXQ4Pn0YBBlmIx58fzKF8C9noVKmTJHfioadXcVbK-9pyIAA; domain=.login.microsoftonline.com; path=/; secure; HttpOnly, x-ms-gateway-slice=productiona; path=/; secure; HttpOnly, stsservicecookie=ests; path=/; secure; HttpOnly
x-ms-request-id: ce4e46fa-96a5-4ba5-a4c4-8f8ce5678abb
client-request-id: 9490d77d-2c4d-4af9-8833-e777265b39da
x-ms-gateway-service-instanceid: ESTSFE_IN_436
X-Content-Type-Options: nosniff
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Powered-By: ASP.NET
;Body: {"error":"invalid_request","error_description":"AADSTS90019: No tenant-identifying information found in either the request or implied by any provided credentials.\r\nTrace ID: ce4e46fa-96a5-4ba5-a4c4-8f8ce5678abb\r\nCorrelation ID: 9490d77d-2c4d-4af9-8833-e777265b39da\r\nTimestamp: 2016-06-19 20:02:47Z","error_codes":[90019],"timestamp":"2016-06-19 20:02:47Z","trace_id":"ce4e46fa-96a5-4ba5-a4c4-8f8ce5678abb","correlation_id":"9490d77d-2c4d-4af9-8833-e777265b39da"};

**Comment by Brian-Ding** [comment]
try to add this in your Configureservices method

>             services.Configure<ForwardedHeadersOptions>(options =>
            {
                options.ForwardedHeaders = ForwardedHeaders.XForwardedProto;
            });

**Comment by joeaudette** [comment]
today my error changed without any changes in my code:

     We're unable to complete your request
     Microsoft account is experiencing technical problems. Please try again later.

I tried also the suggestion from @Brian-Ding but I still get this error.

I will try creating a new web app with the default project template and see if I can get it working there to find out if there is anything specific to my app that is a factor in this problem

**Comment by joeaudette** [comment]
I can confirm that I get the same result with a new application configured today and using a new web app created with the default VS2015 project template with identity and using https for the redirect url.  Adding forwarded headers in ConfigureServices makes no difference

**Comment by Brian-Ding** [comment]
@joeaudette OK, if you are getting 
> We're unable to complete your request
 Microsoft account is experiencing technical problems. Please try again later.

take a look at that url, if will contain the error info, and you can share it here, if you like

**Comment by Brian-Ding** [comment]
As the url says, your redirecturl is incorrect, you may want to check the url when you enter your account name(email) & password, It will contain the info of the redirecturl
![image](https://cloud.githubusercontent.com/assets/11363173/16199640/f7fddc18-373c-11e6-9acf-8760546f7b9c.png)

**Comment by joeaudette** [comment]
my redirect url is configured at apps.dev.microsoft.com as https://localhost:44399/signin-microsoft

which should be correct and I am using the correct client id and secret that corresponds with that configured redirect url

I'm configuring my web app like this:

    var microsoftOptions = new MicrosoftAccountOptions();
            microsoftOptions.ClientId = "myclientid";
            microsoftOptions.ClientSecret = "myclientsecret";
            app.UseMicrosoftAccountAuthentication(microsoftOptions);

is there somewhere else I need to specify my redirect url?
the default callback path for MicrosoftAccountOptions is /signin-microsoft and I assume the middleware is smart enough to resolve that as a fully qualified url if it passes it to Microsoft

**Comment by Brian-Ding** [comment]
1. well , your redirect url registration looks good to me, but I am no expert.
2. your configuration in Method looks good as well,
3. but could you please check you url when you sign in? just to make sure the directurl your web app used matches the one you registered. you can just paste that url here

**Comment by joeaudette** [comment]
It is not showing me the url in the UI, and not prompting me for my password, I guess since I am logged into Microsoft for other services in this browser.
I do see in the url at microsoft it looks like my redirect url is encoded there:

    https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=000000004819E73C&scope=https%3A%2F%2Fgraph.microsoft.com%2Fuser.read&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A55190%2Fsignin-microsoft&state=CfDJ8MLU0mC6GqNNhNLFi_9qYCnCRKJC8pMWrh8P0K7l_Thi4YUqFRDZwkmiW4FBjZG6NkBjKi-tfeeDH3FrmwX4Jx7sYBsncDo3maHt1Q0owaXR_lJws8zROd2Teo4M1fLya52WDIoaP_1GEnrOvpdh4GJuVsdlJ4juDtmgMC_8oQ8zXhmoPDVsAg8RoxjDAr-_qmsYgFjJpITlIWShjT1dfIDWY5hRI9nQ-Xs_HPV1YsLqCflKq5a47kvMmvNzJKGe56OjTnOjLyjFEPzG_lZBbZNkdeDST4Gcc8N66RDyUYoimgMLHsmZ3v44Oqi_MHQzfwotocm9arX3JJFhlF6s7hw

**Comment by joeaudette** [comment]
I'm not sure about the url encoding, it doesn't look like the correct port, but maybe that is just the encoded value?

**Comment by PinpointTownes** [comment]
Wrong port + wrong scheme: `http://localhost:55190/signin-microsoft`.

**Comment by joeaudette** [comment]
so the middleware is not passing the right redirecturi?

should I override the callbackpath with the full url?

**Comment by Brian-Ding** [comment]
yep, if you look at it closer, you will see
> redirect_uri=http%3A%2F%2Flocalhost%3A55190%2Fsignin-microsoft

 which is saying
> http:\\localhost:55190\signin-microsoft

clearly, it is not the same with your registration

**Comment by Brian-Ding** [comment]
there is no need to override redirecturl, just make sure that your server listens at
> https://locaohost:44399/

then it should be fine

**Comment by joeaudette** [comment]
ok, what I was doing wrong was launching the browser on the non secure port without https so it was passing the wrong port.
I must not have had enough coffee this morning.
But now that I tried it with starting out on my local app with the https url, I'm back to the previous error:

An unhandled exception occurred while processing the request.

Exception: OAuth token endpoint failure: Status: BadRequest;Headers: Cache-Control: no-store, no-cache
 Date: Mon, 20 Jun 2016 15:43:57 GMT
 Pragma: no-cache
 P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
 Server: Microsoft-IIS/8.5
 Set-Cookie: esctx=AAABAAAAiL9Kn2Z27UubvWFPbm0gLZWi-0FtK8a-_TB7q7S1NcrsZw7wej-HZCbmHbMPeU6rR2gkcVG1tA4WN4w6wUmn9_Esl5jnzIb2BHZphS1VmKkV2WhhOECCFM3nGrOEEgBmRaYt5v3WruyrAMbo3azk3Nh-vBi65C3I0e3cptXzkPeOn-hub4ew7Z2qJEJB4tfYIAA; domain=.login.microsoftonline.com; path=/; secure; HttpOnly, x-ms-gateway-slice=productiona; path=/; secure; HttpOnly, stsservicecookie=ests; path=/; secure; HttpOnly
 x-ms-request-id: e4421336-f431-4a35-8b17-0f32008ae741
 client-request-id: 17880c47-a92f-44ac-afa8-7fae4a93133d
 x-ms-gateway-service-instanceid: ESTSFE_IN_139
 X-Content-Type-Options: nosniff
 Strict-Transport-Security: max-age=31536000; includeSubDomains
 X-Powered-By: ASP.NET
 ;Body: {"error":"invalid_request","error_description":"AADSTS90019: No tenant-identifying information found in either the request or implied by any provided credentials.\r\nTrace ID: e4421336-f431-4a35-8b17-0f32008ae741\r\nCorrelation ID: 17880c47-a92f-44ac-afa8-7fae4a93133d\r\nTimestamp: 2016-06-20 15:44:00Z","error_codes":[90019],"timestamp":"2016-06-20 15:44:00Z","trace_id":"e4421336-f431-4a35-8b17-0f32008ae741","correlation_id":"17880c47-a92f-44ac-afa8-7fae4a93133d"};

again this is not using a custom app, this is with a new web app using the default template with individual user accounts and I have forwaded headers configured as well ie:

    services.Configure<ForwardedHeadersOptions>(options =>
            {
                options.ForwardedHeaders = Microsoft.AspNetCore.HttpOverrides.ForwardedHeaders.XForwardedProto;
            });

**Comment by Brian-Ding** [comment]
I ran into the same OAuth token endpoint failure before I registered my web application in the new portal, which should the same as you said 
> https://apps.dev.microsoft.com

but everything works ok once I registered my app again in the new portal. Maybe you should delete your app, and try to register another one.

please note that, if you are registered in old style, under Web section, it will show 2 input textbox, instead of only one input like my screen shot

**Comment by Brian-Ding** [comment]
![image](https://cloud.githubusercontent.com/assets/11363173/16201325/749ec1be-3743-11e6-9b0d-1ca401cc5e35.png)

**Comment by joeaudette** [comment]
I think you are on to something, for me I have 2 sections for adding apps and all of mine are under the Live SDK Apps section and they have 2 text inputs, so maybe I am making them in the wrong place.

But when I try to add an app at the top of the page in the main section it does not automatically create any clientsecret and I only see buttons for creating a password or a key pair which doesn't seem like what I want

**Comment by Brian-Ding** [comment]
that is exactly the ways it is. it will show the clientid automatically, for the clientsecret, just click on Generate New Password, and copy that to somewhere safe.

that should solve your problem now.

Best of luck

**Comment by joeaudette** [comment]
ok that solved it, create password button did the trick, sorry for wasting everyone's time with my stupidity.
I think the mismatch of labeling for clientsecret vs password is what made me think I was in the wrong place so I kept doing it wrong, I thought if I was at the right url for creating apps I could not be doing it wrong but I was doing it wrong since it is still possible to create the old version apps there

**Comment by joeaudette** [comment]
thanks for all the help!

**Comment by Brian-Ding** [comment]
great！

I think they may close the issue now, while open a new one called "change generate new password to generate new clientsecret"



Just kidding

**Comment by Tratcher** [comment]
Thanks for helping sort this out everybody.

**Comment by qin-nz** [comment]
Hi,everybody.
I have the same error.
I think everything is correct but I still get the error.

apps.dev.microsoft.com
![image](https://cloud.githubusercontent.com/assets/6998071/17664052/d3ab9662-6323-11e6-99f2-5d33f02ca3ae.png)
appsettings
![image](https://cloud.githubusercontent.com/assets/6998071/17664063/e139cec0-6323-11e6-97fd-7d6cde27f03e.png)
Configure
![image](https://cloud.githubusercontent.com/assets/6998071/17664073/f6fc50e8-6323-11e6-9232-6ae0c26a21d4.png)
ConfigureService
![image](https://cloud.githubusercontent.com/assets/6998071/17664076/01d79450-6324-11e6-880e-da2b67b717ee.png)

signin link
```
https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=000000004C1A2232&scope=https%3A%2F%2Fgraph.microsoft.com%2Fuser.read&response_type=code&redirect_uri=https%3A%2F%2Fwww-dev.email2rss.net%2Fsignin-microsoft&state=CfDJ8GxApjN-hBpFjFO1TcsIQ1EwcTXQijv1CN3RG9V3H0enoS0mP-ikVi0FmLi70Ju-a4evx9xDpA2jV5gYFFTO3zz2eGJ0aaGF91QAZfVYAkm9WTrXw7B_LHCXv-ckfaWHMdM9dArXgGtIGrjSvR91is5dAdOQSf57XMP0JFnkLRp4tIl3V06hjtEVZ3-K4cycx-IGUqwkA7XjcgJtls9tTr92FT6pomSP5o_JcfSrx_uV0CEpn214H9baqU7pW0y1VRbmdaBsOe8IVKZiyx5XBFNgCxxpMJBR3xGgTU-K8y_HVC8ps-hYp7dPIclyJaSkiffwxTeQxiY1y97HJGtzNrA
```

 @Brian-Ding Can you help to me solve it.

**Comment by Brian-Ding** [comment]
@qin-nz your application id shows that you are not registering with the lastest version, please delete your app @ apps.dev.microsoft.com and register a new one at the same website

**Comment by Brian-Ding** [comment]
the application id should be in this format
![image](https://cloud.githubusercontent.com/assets/11363173/17757752/feebe5da-651b-11e6-8c59-34552b6eee4d.png)

**Comment by qin-nz** [comment]
@Brain-Ding Oh, thanks.
I just create a live sdk app early.
![image](https://cloud.githubusercontent.com/assets/6998071/17769431/164dd766-656b-11e6-8089-3c3fbb50d806.png)

**Comment by LukaszDev** [comment]
Check if you have enabled 'Live SDK support' checkbox in settings of your new Application?
